apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  labels:
    app: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
        sermant-injection: enabled
    spec:
      containers:
        - name: service-c
          image: service-c:1.0.0
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: default-secret