apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-gray
  labels:
    app: service-b-gray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b-gray
  template:
    metadata:
      labels:
        app: service-b-gray
        sermant-injection: enabled
    spec:
      containers:
        - name: service-b-gray
          image: service-b:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: "SERVICE_META_PARAMETERS"
              value: "group:gray"
            - name: "NACOS_ADDRESS"
              value: "127.0.0.1:8848"
      imagePullSecrets:
        - name: default-secret