apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
        sermant-injection: enabled
    spec:
      containers:
        - name: service-a
          image: service-a:1.0.0
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: default-secret